import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// Pasteboard types that mean "do not record this" — password managers and
/// transient-copy tools set them. Honouring these is table stakes.
enum PBType {
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let autoGen   = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let onePass   = NSPasteboard.PasteboardType("com.agilebits.onepassword")
    static let petermaurer = NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    static let generator = NSPasteboard.PasteboardType("Pasteboard generator type")
    static let keeweb    = NSPasteboard.PasteboardType("net.antelle.keeweb")

    static let confidential: [NSPasteboard.PasteboardType] =
        [concealed, onePass, petermaurer, generator, keeweb]
}

final class Watcher {
    /// `Klipvault --probe` turns this on to explain, out loud, why a copy was or wasn't kept.
    static var debug = false
    private static func log(_ m: @autoclosure () -> String) { if debug { print("  " + m()) } }
    private let pb = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?
    private let vault: Vault
    var onCapture: ((ClipRecord) -> Void)?

    init(vault: Vault) {
        self.vault = vault
        self.lastChange = pb.changeCount
    }

    func start() {
        timer?.invalidate()
        let interval = max(0.1, D.dbl(D.pollInterval))
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stop() { timer?.invalidate(); timer = nil }
    func restart() { start() }

    /// Marks the next pasteboard change as ours so we don't re-record our own paste.
    func ignoreNextChange() { lastChange = pb.changeCount + 1 }

    private func poll() {
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        guard !vault.isLocked else { return }
        guard let rec = capture() else { return }
        onCapture?(rec)
    }

    // MARK: capture

    private func shouldSkip() -> Bool {
        let types = Set(pb.types ?? [])
        if D.bool(D.ignoreTransient), types.contains(PBType.transient) || types.contains(PBType.autoGen) { return true }
        if D.bool(D.ignoreConfidential), PBType.confidential.contains(where: { types.contains($0) }) { return true }
        if let front = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           D.lines(D.ignoredApps).contains(where: { $0.caseInsensitiveCompare(front) == .orderedSame }) { return true }
        return false
    }

    private func ignoredByRegex(_ s: String) -> Bool {
        for p in D.lines(D.ignoreRegexes) {
            guard let re = try? NSRegularExpression(pattern: p) else { continue }
            if re.firstMatch(in: s, options: [], range: NSRange(s.startIndex..., in: s)) != nil { return true }
        }
        return false
    }

    func capture() -> ClipRecord? {
        if shouldSkip() { Self.log("skipped: ignore rule or transient/confidential marker"); return nil }
        let app = NSWorkspace.shared.frontmostApplication
        var rec = ClipRecord()
        rec.appBundle = app?.bundleIdentifier
        rec.appName = app?.localizedName

        // 1. Files
        if D.bool(D.storeFiles),
           let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.path }
            rec.kind = .files
            rec.text = paths.joined(separator: "\n")
            rec.title = urls.count == 1 ? urls[0].lastPathComponent
                                        : "\(urls.count) files — \(urls[0].lastPathComponent), …"
            rec.bytes = rec.text!.utf8.count
            rec.hash = Self.digest(Data(rec.text!.utf8))
            if let img = urls.first.flatMap({ NSWorkspace.shared.icon(forFile: $0.path) }) {
                rec.thumb = Self.png(img, maxDim: 128)
            }
            return rec
        }

        // 2. Image
        if D.bool(D.storeImages), let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            guard let img = NSImage(data: data) else { Self.log("skipped image: \(data.count) bytes would not decode"); return nil }
            let cap = D.int(D.maxImageMB) * 1024 * 1024
            if cap > 0 && data.count > cap { Self.log("skipped image: \(data.count) bytes over the \(cap) byte cap"); return nil }
            rec.kind = .image
            rec.bytes = data.count
            rec.pixelW = Int(img.size.width); rec.pixelH = Int(img.size.height)
            rec.title = "Image \(rec.pixelW)×\(rec.pixelH) — \(Self.human(data.count))"
            rec.thumb = Self.png(img, maxDim: 256)   // ponytail: rows cap at 120pt, so 256 covers retina
            rec.hash = Self.digest(data)
            rec.blob = vault.writeBlob(data)
            if rec.blob == nil { Self.log("skipped image: could not write encrypted blob (vault locked?)"); return nil }
            return rec
        }

        // 3. Text (with rich flavours preserved)
        guard D.bool(D.storeText) else { Self.log("skipped: text capture is off"); return nil }
        guard let s = pb.string(forType: .string) else { Self.log("skipped: nothing on the pasteboard we handle (types: \((pb.types ?? []).map(\.rawValue).joined(separator: ", ")))"); return nil }
        let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
        if D.bool(D.ignoreOnlyWhitespace) && trimmed.isEmpty { Self.log("skipped: whitespace only"); return nil }
        let minL = D.int(D.minLength), maxL = D.int(D.maxLength)
        if minL > 0 && s.count < minL { return nil }
        if maxL > 0 && s.count > maxL { return nil }
        let capBytes = D.int(D.maxTextKB) * 1024
        if capBytes > 0 && s.utf8.count > capBytes { return nil }
        if ignoredByRegex(s) { Self.log("skipped: matched an ignore pattern"); return nil }

        rec.kind = .text
        rec.text = s
        rec.bytes = s.utf8.count
        rec.title = Self.oneLine(trimmed.isEmpty ? s : trimmed)
        rec.hash = Self.digest(Data(s.utf8))
        if let rtf = pb.data(forType: .rtf), rtf.count < 256 * 1024 { rec.rtf = rtf }
        if let html = pb.data(forType: .html), html.count < 256 * 1024 { rec.html = html }
        if D.bool(D.detectSecrets), SecretScanner.match(s) != nil {
            rec.sensitive = true
            if D.bool(D.maskSensitive) { rec.title = "🔒 Sensitive — \(s.count) characters hidden" }
        }
        return rec
    }

    // MARK: writing back

    /// Puts a record on the system pasteboard. `plain` drops rich formatting.
    func writeToPasteboard(_ rec: ClipRecord, plain: Bool) {
        ignoreNextChange()
        pb.clearContents()
        switch rec.kind {
        case .files:
            let urls = (rec.text ?? "").split(separator: "\n").map { URL(fileURLWithPath: String($0)) }
            pb.writeObjects(urls as [NSPasteboardWriting])
        case .image:
            if let name = rec.blob, let data = vault.readBlob(name) {
                pb.setData(data, forType: .png)
                if let img = NSImage(data: data), let tiff = img.tiffRepresentation { pb.setData(tiff, forType: .tiff) }
            } else if let t = rec.thumb {
                pb.setData(t, forType: .png)
            }
        case .text:
            if !plain, let rtf = rec.rtf { pb.setData(rtf, forType: .rtf) }
            if !plain, let html = rec.html { pb.setData(html, forType: .html) }
            pb.setString(rec.text ?? "", forType: .string)
        }
        lastChange = pb.changeCount
    }

    /// Sends ⌘V to whatever app is frontmost. Requires Accessibility permission;
    /// without it the content is still on the clipboard, so nothing is lost.
    static func sendPaste() {
        guard AXIsProcessTrusted() else { return }
        let src = CGEventSource(stateID: .combinedSessionState)
        src?.setLocalEventsFilterDuringSuppressionState(.permitLocalMouseEvents, state: .eventSuppressionStateSuppressionInterval)
        let down = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: true)
        let up = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: false)
        down?.flags = .maskCommand
        up?.flags = .maskCommand
        down?.post(tap: .cgAnnotatedSessionEventTap)
        up?.post(tap: .cgAnnotatedSessionEventTap)
    }

    // MARK: helpers

    static func digest(_ d: Data) -> String {
        SHA256.hash(data: d).compactMap { String(format: "%02x", $0) }.joined()
    }

    static func oneLine(_ s: String) -> String {
        let collapsed = s.split(whereSeparator: \.isNewline).first.map(String.init) ?? s
        let t = collapsed.trimmingCharacters(in: .whitespaces)
        return t.count > 300 ? String(t.prefix(300)) + "…" : t
    }

    static func human(_ b: Int) -> String {
        ByteCountFormatter.string(fromByteCount: Int64(b), countStyle: .file)
    }

    static func png(_ img: NSImage, maxDim: CGFloat) -> Data? {
        let w = img.size.width, h = img.size.height
        guard w > 0, h > 0 else { return nil }
        let scale = min(1, maxDim / max(w, h))
        let size = NSSize(width: max(1, w * scale), height: max(1, h * scale))
        let out = NSImage(size: size)
        out.lockFocus()
        img.draw(in: NSRect(origin: .zero, size: size),
                 from: NSRect(origin: .zero, size: img.size),
                 operation: .copy, fraction: 1)
        out.unlockFocus()
        guard let tiff = out.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
